import type { ReadingClub, CandidateBook } from '../../shared/types';

const generateId = () => Math.random().toString(36).substring(2, 9);

export const mockReadingClubs: ReadingClub[] = [
  {
    id: 'rc-001',
    book: {
      id: 'book-001',
      title: '百年孤独',
      author: '加西亚·马尔克斯',
      description: '《百年孤独》是魔幻现实主义文学的代表作，描写了布恩迪亚家族七代人的传奇故事，以及加勒比海沿岸小镇马孔多的百年兴衰。',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=classical%20book%20cover%20design%20for%20One%20Hundred%20Years%20of%20Solitude%20magical%20realism%20style&image_size=portrait_4_3',
      totalPages: 360,
    },
    chapters: [
      {
        id: 'ch-001',
        readingClubId: 'rc-001',
        title: '第一章：马孔多的创建',
        pageRange: '第 1-45 页',
        startPage: 1,
        endPage: 45,
        deadline: '2026-06-10',
        order: 1,
      },
      {
        id: 'ch-002',
        readingClubId: 'rc-001',
        title: '第二章：家族的起源',
        pageRange: '第 46-90 页',
        startPage: 46,
        endPage: 90,
        deadline: '2026-06-17',
        order: 2,
      },
      {
        id: 'ch-003',
        readingClubId: 'rc-001',
        title: '第三章：外来者的到来',
        pageRange: '第 91-135 页',
        startPage: 91,
        endPage: 135,
        deadline: '2026-06-24',
        order: 3,
      },
      {
        id: 'ch-004',
        readingClubId: 'rc-001',
        title: '第四章：战争的阴影',
        pageRange: '第 136-180 页',
        startPage: 136,
        endPage: 180,
        deadline: '2026-07-01',
        order: 4,
      },
      {
        id: 'ch-005',
        readingClubId: 'rc-001',
        title: '第五章：命运的轮回',
        pageRange: '第 181-225 页',
        startPage: 181,
        endPage: 225,
        deadline: '2026-07-08',
        order: 5,
      },
      {
        id: 'ch-006',
        readingClubId: 'rc-001',
        title: '第六章：孤独的终结',
        pageRange: '第 226-360 页',
        startPage: 226,
        endPage: 360,
        deadline: '2026-07-15',
        order: 6,
      },
    ],
    offlineEvents: [
      {
        id: 'event-001',
        readingClubId: 'rc-001',
        title: '第一次线下见面会',
        date: '2026-06-15',
        time: '19:30',
        location: '城市书房·三楼多功能厅',
        description: '讨论前两章的阅读感受，分享各自对魔幻现实主义的理解。',
        attendeeCount: 12,
      },
      {
        id: 'event-002',
        readingClubId: 'rc-001',
        title: '中期读书分享会',
        date: '2026-06-29',
        time: '19:30',
        location: '城市书房·三楼多功能厅',
        description: '结合第三、四章，探讨书中的战争描写和历史隐喻。',
        attendeeCount: 15,
      },
    ],
    discussions: [
      {
        id: 'disc-001',
        readingClubId: 'rc-001',
        chapterId: 'ch-001',
        userId: 'user-002',
        userName: '林小雨',
        type: 'comment',
        content: '第一章就被马尔克斯的叙事方式深深吸引了！那句"多年以后，面对行刑队，奥雷里亚诺·布恩迪亚上校将会回想起父亲带他去见识冰块的那个遥远的下午"简直是神来之笔，一句话就包含了过去、现在和未来三个时间维度。',
        isSpoiler: false,
        createdAt: '2026-06-05T10:30:00Z',
        likes: 8,
      },
      {
        id: 'disc-002',
        readingClubId: 'rc-001',
        chapterId: 'ch-001',
        userId: 'user-003',
        userName: '张明远',
        type: 'question',
        content: '大家怎么理解吉普赛人带来的磁铁、放大镜和冰块这些意象？它们仅仅是新奇的物品，还是有更深的象征意义？尤其是冰块，为什么会让孩子们那么着迷？',
        isSpoiler: false,
        createdAt: '2026-06-06T14:20:00Z',
        likes: 5,
      },
      {
        id: 'disc-003',
        readingClubId: 'rc-001',
        chapterId: 'ch-001',
        userId: 'user-004',
        userName: '王思琪',
        type: 'excerpt',
        content: '"世界新生伊始，许多事物还没有名字，提到的时候尚需用手指指点点。" 这句话太美了，让我想到人类文明之初的状态，也暗示了整个马孔多的故事就是一个从创世到毁灭的循环。',
        isSpoiler: false,
        createdAt: '2026-06-06T20:15:00Z',
        likes: 12,
      },
      {
        id: 'disc-004',
        readingClubId: 'rc-001',
        chapterId: 'ch-002',
        userId: 'user-005',
        userName: '陈浩然',
        type: 'comment',
        content: '乌尔苏拉真是这个家族的支柱！她活了那么久，见证了整个家族的兴衰。相比之下，家族里的男性们都沉浸在自己的世界里，不是做实验就是打仗，只有乌尔苏拉在支撑着这个家。',
        isSpoiler: true,
        createdAt: '2026-06-09T09:45:00Z',
        likes: 6,
      },
      {
        id: 'disc-005',
        readingClubId: 'rc-001',
        chapterId: 'ch-002',
        userId: 'user-006',
        userName: '李雅婷',
        type: 'question',
        content: '为什么家族的名字总是在重复？奥雷里亚诺和阿尔卡蒂奥这两个名字不断出现，是不是暗示了命运的轮回？感觉每一代人都在重复上一代的错误。',
        isSpoiler: false,
        createdAt: '2026-06-10T16:30:00Z',
        likes: 9,
      },
      {
        id: 'disc-006',
        readingClubId: 'rc-001',
        chapterId: 'ch-001',
        userId: 'user-007',
        userName: '赵子轩',
        type: 'comment',
        content: '我觉得马孔多这个小镇本身就是一个象征，它从一个与世隔绝的世外桃源，逐渐被外界文明侵蚀，最后走向毁灭。这不正是整个拉丁美洲历史的缩影吗？',
        isSpoiler: true,
        createdAt: '2026-06-07T11:20:00Z',
        likes: 15,
      },
    ],
    organizerId: 'user-001',
    organizerName: '李书文',
    status: 'ongoing',
    startDate: '2026-06-01',
    endDate: null,
    memberCount: 28,
  },
  {
    id: 'rc-002',
    book: {
      id: 'book-002',
      title: '人类简史',
      author: '尤瓦尔·赫拉利',
      description: '从认知革命、农业革命到科学革命，作者用独特的视角审视人类历史，探讨我们是如何成为地球的主宰者，以及未来可能走向何方。',
      coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=book%20cover%20design%20for%20Sapiens%20A%20Brief%20History%20of%20Humankind%20anthropology%20style&image_size=portrait_4_3',
      totalPages: 440,
    },
    chapters: [
      {
        id: 'ch-011',
        readingClubId: 'rc-002',
        title: '第一章：认知革命',
        pageRange: '第 1-70 页',
        startPage: 1,
        endPage: 70,
        deadline: '2026-05-20',
        order: 1,
      },
      {
        id: 'ch-012',
        readingClubId: 'rc-002',
        title: '第二章：农业革命',
        pageRange: '第 71-140 页',
        startPage: 71,
        endPage: 140,
        deadline: '2026-05-27',
        order: 2,
      },
      {
        id: 'ch-013',
        readingClubId: 'rc-002',
        title: '第三章：人类的融合统一',
        pageRange: '第 141-210 页',
        startPage: 141,
        endPage: 210,
        deadline: '2026-06-03',
        order: 3,
      },
      {
        id: 'ch-014',
        readingClubId: 'rc-002',
        title: '第四章：科学革命',
        pageRange: '第 211-300 页',
        startPage: 211,
        endPage: 300,
        deadline: '2026-06-10',
        order: 4,
      },
      {
        id: 'ch-015',
        readingClubId: 'rc-002',
        title: '第五章：智人末日',
        pageRange: '第 301-440 页',
        startPage: 301,
        endPage: 440,
        deadline: '2026-06-17',
        order: 5,
      },
    ],
    offlineEvents: [
      {
        id: 'event-003',
        readingClubId: 'rc-002',
        title: '开篇讨论会',
        date: '2026-05-18',
        time: '20:00',
        location: '线上会议室',
        description: '讨论认知革命对人类发展的意义。',
        attendeeCount: 20,
      },
      {
        id: 'event-004',
        readingClubId: 'rc-002',
        title: '总结分享会',
        date: '2026-06-20',
        time: '19:30',
        location: '城市书房·二楼讨论区',
        description: '整本书阅读分享，探讨人类未来的可能方向。',
        attendeeCount: 18,
      },
    ],
    discussions: [
      {
        id: 'disc-011',
        readingClubId: 'rc-002',
        chapterId: 'ch-011',
        userId: 'user-008',
        userName: '吴晓东',
        type: 'comment',
        content: '作者说"虚构故事"让智人得以大规模合作，这个观点太有启发性了！公司、国家、宗教其实都是集体想象的产物，但它们却能让成千上万的陌生人合作无间。',
        isSpoiler: false,
        createdAt: '2026-05-15T14:20:00Z',
        likes: 23,
      },
      {
        id: 'disc-012',
        readingClubId: 'rc-002',
        chapterId: 'ch-012',
        userId: 'user-009',
        userName: '郑晓彤',
        type: 'question',
        content: '作者说农业革命是"历史上最大的骗局"，农民比采集者更辛苦，营养也更差。那我们为什么会选择农业呢？是偶然还是必然？',
        isSpoiler: false,
        createdAt: '2026-05-22T09:10:00Z',
        likes: 18,
      },
    ],
    organizerId: 'user-001',
    organizerName: '李书文',
    status: 'ended',
    startDate: '2026-05-10',
    endDate: '2026-06-20',
    memberCount: 35,
  },
];

export const mockCandidateBooks: CandidateBook[] = [
  {
    id: 'cand-001',
    title: '活着',
    author: '余华',
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=book%20cover%20design%20for%20To%20Live%20by%20Yu%20Hua%20minimalist%20style&image_size=portrait_4_3',
    votes: 12,
  },
  {
    id: 'cand-002',
    title: '三体',
    author: '刘慈欣',
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=book%20cover%20design%20for%20The%20Three%20Body%20Problem%20sci%20fi%20space&image_size=portrait_4_3',
    votes: 18,
  },
  {
    id: 'cand-003',
    title: '小王子',
    author: '安托万·德·圣-埃克苏佩里',
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=book%20cover%20design%20for%20The%20Little%20Prince%20whimsical%20illustration&image_size=portrait_4_3',
    votes: 8,
  },
  {
    id: 'cand-004',
    title: '挪威的森林',
    author: '村上春树',
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=book%20cover%20design%20for%20Norwegian%20Wood%20Japanese%20literary%20style&image_size=portrait_4_3',
    votes: 15,
  },
];

export function getMockReadingClubs(): ReadingClub[] {
  return mockReadingClubs;
}

export function getMockReadingClubById(id: string): ReadingClub | undefined {
  return mockReadingClubs.find(rc => rc.id === id);
}

export function getMockCandidateBooks(): CandidateBook[] {
  return mockCandidateBooks;
}
